In [1]:
# Задача 44: В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
print(data)

   whoAmI
0   human
1   robot
2   robot
3   robot
4   human
5   robot
6   human
7   robot
8   human
9   robot
10  human
11  human
12  robot
13  robot
14  human
15  human
16  human
17  human
18  robot
19  robot

In [2]:
# Как бы получилось с get_dummies
pd.get_dummies(data['whoAmI'])

    human  robot
0       1      0
1       0      1
2       0      1
3       0      1
4       1      0
5       0      1
6       1      0
7       0      1
8       1      0
9       0      1
10      1      0
11      1      0
12      0      1
13      0      1
14      1      0
15      1      0
16      1      0
17      1      0
18      0      1
19      0      1

In [3]:
# с помощью библиотеки sklearn

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(handle_unknown='ignore')
encoder_data = pd.DataFrame(encoder.fit_transform(data[['whoAmI']]).toarray())
final_data = data.join(encoder_data)
print(final_data)

   whoAmI    0    1
0   human  1.0  0.0
1   robot  0.0  1.0
2   robot  0.0  1.0
3   robot  0.0  1.0
4   human  1.0  0.0
5   robot  0.0  1.0
6   human  1.0  0.0
7   robot  0.0  1.0
8   human  1.0  0.0
9   robot  0.0  1.0
10  human  1.0  0.0
11  human  1.0  0.0
12  robot  0.0  1.0
13  robot  0.0  1.0
14  human  1.0  0.0
15  human  1.0  0.0
16  human  1.0  0.0
17  human  1.0  0.0
18  robot  0.0  1.0
19  robot  0.0  1.0

In [4]:
final_data.drop('whoAmI', axis= 1, inplace= True)
final_data.columns = ['human', 'robot']
print(final_data)

    human  robot
0     1.0    0.0
1     0.0    1.0
2     0.0    1.0
3     0.0    1.0
4     1.0    0.0
5     0.0    1.0
6     1.0    0.0
7     0.0    1.0
8     1.0    0.0
9     0.0    1.0
10    1.0    0.0
11    1.0    0.0
12    0.0    1.0
13    0.0    1.0
14    1.0    0.0
15    1.0    0.0
16    1.0    0.0
17    1.0    0.0
18    0.0    1.0
19    0.0    1.0